#!/usr/bin/env bash
# Pure Homebrew formula renderers for scripts/update-formula.sh. Sourced.
# Each public function echoes the full Formula/*.rb contents. No side effects.

# _formula_os_blocks <base_url> <d_amd64> <d_arm64> <l_amd64> <l_arm64>
# Shared on_macos/on_linux url+sha blocks. Internal helper.
_formula_os_blocks() {
  cat <<RB
  on_macos do
    if Hardware::CPU.intel?
      url "${1}/tele_darwin_amd64.tar.gz"
      sha256 "${2}"
    end
    if Hardware::CPU.arm?
      url "${1}/tele_darwin_arm64.tar.gz"
      sha256 "${3}"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "${1}/tele_linux_amd64.tar.gz"
      sha256 "${4}"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${1}/tele_linux_arm64.tar.gz"
      sha256 "${5}"
    end
  end
RB
}

# render_stable_formula <owner> <version> <base_url> <d_amd64> <d_arm64> <l_amd64> <l_arm64> <extra_line>
# <extra_line> is an already-indented Ruby line injected after `version`
# (used for `deprecate!` on the legacy tap); pass "" for none.
render_stable_formula() {
  local owner=$1 version=$2 base=$3 da=$4 dr=$5 la=$6 lr=$7 extra=${8:-}
  cat <<RB
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh. DO NOT EDIT.
class Tele < Formula
  desc "TUI Telegram client"
  homepage "https://github.com/${owner}/tele"
  version "${version}"
${extra}
$(_formula_os_blocks "$base" "$da" "$dr" "$la" "$lr")

  def install
    bin.install "tele"
  end

  test do
    system "#{bin}/tele", "--version"
  end
end
RB
}

# render_beta_formula <owner> <version> <base_url> <d_amd64> <d_arm64> <l_amd64> <l_arm64>
# Beta package: separate binary and state, coexists with stable — no
# conflicts_with, no deprecate!.
render_beta_formula() {
  local owner=$1 version=$2 base=$3 da=$4 dr=$5 la=$6 lr=$7
  cat <<RB
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh. DO NOT EDIT.
class TeleBeta < Formula
  desc "TUI Telegram client (beta channel)"
  homepage "https://github.com/${owner}/tele"
  version "${version}"
$(_formula_os_blocks "$base" "$da" "$dr" "$la" "$lr")

  def install
    bin.install "tele" => "tele-beta"
  end

  test do
    system "#{bin}/tele-beta", "--version"
  end
end
RB
}
